### PR TITLE
Manylinux

### PR DESCRIPTION
**Pull request by jeancochrane**
Trying this PR again to see if Travis will receive the request this time.

### CODE REVIEW

**Comment by jeancochrane** [comment]
Builds are taking a long time and then failing to reach quay.io because of the [current S3 outage](https://www.traviscistatus.com/incidents/hmwq9yy5dh9d), I think. Going to wait until that clears up and then rebuild this PR.

**Comment by fgregg** [comment]
@jeancochrane we don't actually need manylinx builds for usaddress, since it doesn't distribute any binary files.  We already have a universal wheel for usaddress. https://pypi.python.org/pypi/usaddress

We do need it on usaddress though.

**Comment by jeancochrane** [comment]
Hm, OK. #47 seemed to imply that python-crfsuite necessitated a manylinux build? This is a bit over my head, so I leave the call up to you.

**Comment by fgregg** [comment]
So, what we want to do is help @mbatchkarov provide a manylinux build for [python-crfsuite](https://pypi.python.org/pypi/python-crfsuite).

**Comment by jeancochrane** [comment]
Ahhhh, OK. I think I see what's going on now – my mistake. Shall we kill this PR?

**Comment by fgregg** [comment]
yup!

**Pull request closed without merging**
