### PR TITLE
update to training data

### PR DESCRIPTION
**Pull request by markbaas**
Parses properly:
198 E 161st St
District Atty Bronx Cty
Bronx, NY, 10451-3536

### CODE REVIEW

**Comment by cathydeng** [comment]
shouldn't `District Atty Bronx Cty` be labeled as `Recipient`, rather than as `BuildingName`?

**Comment by markbaas** [comment]
Well... it is the Bronx District Attorney Office. So I suppose that is a building.

**Comment by cathydeng** [comment]
the name of an office within a building should still be a recipient, to be consistent with our existing training data. for the `BuildingName` label, we typically have stuff like 'first union tower' or 'first national bank building'

**Comment by markbaas** [comment]
Alright updated it to recipient!

**Comment by cathydeng** [comment]
thx @markbaas!

**Pull request merged**
