### PR TITLE
Issue 60: address number prefix sample data

### PR DESCRIPTION
**Pull request by darrell**
Adds some sample data for testing issue #60

### CODE REVIEW

**Comment by Downchuck** [comment]
What's the status on this open issue?

**Comment by cathydeng** [comment]
hey @darrell & @Downchuck,

the training example

`<AddressString><AddressNumberPrefix>0</AddressNumberPrefix><AddressNumber>1</AddressNumber><StreetNamePreDirectional>SW</StreetNamePreDirectional><StreetName>RICHARDSON</StreetName><StreetNamePostType>ST</StreetNamePostType><PlaceName>Portland</PlaceName><StateName>OR</StateName></AddressString>
`

would correspond to the raw string `0 1 SW RICHARDSON ST Portland OR`, not `01 SW RICHARDSON ST Portland OR` (like the example in issue 60)

these examples would train the address parser to recognize a sole 0 as an address number prefix, but still wouldn't split out a 0 from the beginning of an address number, b/c that would have to happen in a post-processing step.

are address prefixes ever split out in real Portland addresses, e.g. is `0 1 SW RICHARDSON ST` a valid address?

**Comment by darrell** [comment]
No, to the best of my knowledge `0 1 SW RICHARDSON ST ` would not be "correct".

I think that if it parses to the standard (i.e. the 0 is treated AddressNumberPrefix), then it's reasonable to leave it to the post-processing to merge those fields without the space. However, IIRC, all of the examples in the standard have no space between the AddressNumberPrefix and the AddressNumber.

**Comment by Downchuck** [comment]
On Portland: http://zehnkatzen.blogspot.com/2005/07/geography-address-nerd-on-zero-hundred.html

**Pull request closed without merging**
